/*
 * generated by Xtext
 */
package br.ufpe.cin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TupiUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return br.ufpe.cin.ui.internal.TupiActivator.getInstance().getInjector("br.ufpe.cin.Tupi");
	}
	
}
