/*
 * generated by Xtext
 */
package br.ufpe.cin.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.ufpe.cin.services.TupiGrammarAccess;

public class TupiParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TupiGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.ufpe.cin.parser.antlr.internal.InternalTupiParser createParser(XtextTokenStream stream) {
		return new br.ufpe.cin.parser.antlr.internal.InternalTupiParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TupiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TupiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
