/**
 * generated by Xtext
 */
package br.ufpe.cin.ui.contentassist;

import br.ufpe.cin.ui.contentassist.AbstractTupiProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TupiProposalProvider extends AbstractTupiProposalProvider {
}
