/*
 * generated by Xtext
 */
package br.ufpe.cin;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TupiStandaloneSetup extends TupiStandaloneSetupGenerated{

	public static void doSetup() {
		new TupiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

