/*
 * generated by Xtext
 */
package br.ufpe.cin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TupiRuntimeModule extends br.ufpe.cin.AbstractTupiRuntimeModule {

}
