/*
 * generated by Xtext
 */
package br.ufpe.cin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TupiUiModule extends br.ufpe.cin.ui.AbstractTupiUiModule {
	public TupiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
