/**
 * generated by Xtext
 */
package br.ufpe.cin.validation;

import br.ufpe.cin.validation.AbstractTupiValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TupiValidator extends AbstractTupiValidator {
}
